name: MLOps CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/

  train-and-quantize:
    runs-on: ubuntu-latest
    needs: test-suite
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create model directory
        run: mkdir -p model

      - name: Train model
        run: python src/train.py

      - name: Quantize model
        run: python src/quantize.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            model/linear_model.joblib
            model/quant_params.joblib
            model/unquant_params.joblib

  build-and-test-container:
    runs-on: ubuntu-latest
    needs: train-and-quantize
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t mlops-linear .

      - name: Run container
        run: docker run --rm mlops-linear

      - name: Verify predictions
        run: docker run --rm --entrypoint python mlops-linear src/predict.py
